[package]
name = "Elden_ring_compteur"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.14.0"
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging"] }
windows-core = "0.62.2"
